# Generated by Django 3.0.6 on 2021-06-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_account'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
