# Generated by Django 3.0.6 on 2021-06-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210619_2224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
