# Generated by Django 3.0.6 on 2021-06-19 17:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210619_2237'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
