# Generated by Django 3.0.6 on 2021-06-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210619_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
