# Generated by Django 3.0.6 on 2021-06-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='english',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='physics',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='science',
        ),
    ]
